http:
  port: '8081'
  
american:
  host: "training-american-api-shah.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "146c486bd68045d98b28b7b25449fe77"
  client_secret:  "1E741396a2324C13a5B8676A0198058A"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"